spring:
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672
    username: root
    password: root
    virtual-host: /
    #配置连接超时15s
    connection-timeout: 15000

    ##设置消息确认模式
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

    ##配置数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springbootrabbitmq?useUnicode=true&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xq1996621
server:
  port: 8000
  servlet:
    path: /
mybatis:
  type-aliases-package: com.shiqi.entity
  mapper-locations: classpath:mapper/*.xml











